### ISSUE TITLE
Unable to locate package.

### ISSUE THREAD

**Issue by bisaalz** [Yisus7u7/termux-desktop-xfce#103]
My Termux is uptodate with pkg update. I am using latest fdroid termux
xfce desktop is uptodate.
but it is still showing unable to locate package if i try to install any app using apt install. 
i can't even do apt install update. it only happens n this distro but not in andronix distro

**Comment by st0rmc4non** [comment]
There's no `apt install update` command, what are you talking about

Also, **please do not try to execute this command on distro, as this is meant for native termux**

**Comment by bisaalz** [comment]
> There's no `apt install update` command, what are you talking about
> 
> Also, **please do not try to execute this command on distro, as this is meant for native termux**
Then how do i install software. I tried doing apt install firefox it says unable to locate package. I tried vlc same result, gimp. same result . I can't install any software.

**Comment by Yisus7u7** [comment]
@bisaalz I remind you that termux x11 is a project still in development and many components are missing, apart from its big difference with proot is that termux is native.

Several applications are not yet available, but as an alternative to what you need, you can use otter-browser, mtpaint and parole

**Comment by Yisus7u7** [comment]
@bisaalz You can use the software store to view the catalog of apps:

`apt install synaptic`
