### ISSUE TITLE
How to Uninstall..

### ISSUE THREAD

**Issue by JanuelDongito** [Yisus7u7/termux-desktop-xfce#107]
Due to storage limitations I don't know how to uninstall it it takes upto 1.5GB storage and i want to remove it can someone teach me??

**Comment by shruuub** [comment]
https://github.com/Yisus7u7/termux-desktop-xfce/issues/99

```
apt autopurge termux-desktop-xfce xfce* tigervnc geany && rm -rf Pictures/ Desktop/ Public/ Documents/ Downloads/ Videos/ Templates/
```
Should do the trick

**Comment by shruuub** [comment]
https://github.com/Yisus7u7/termux-desktop-xfce/issues/99

```
apt autopurge termux-desktop-xfce xfce* tigervnc geany && rm -rf Pictures/ Desktop/ Public/ Documents/ Downloads/ Videos/ Templates/
```
Should do the trick

**Comment by jynn12** [comment]
@Yisus7u7 You can now close this issue.
