### ISSUE TITLE
Issue's on Installing Programs

### ISSUE THREAD

**Issue by JanuelDongito** [Yisus7u7/termux-desktop-xfce#108]

**Comment by JanuelDongito** [comment]
After I installed Some apps example DOSBox but it didn't shown in start menu is there any workaround to create a desktop shortcut or a way to launch it...
![Screenshot_20220601-232643_VNC Viewer](https://user-images.githubusercontent.com/92237697/171443990-856eaeb3-8a64-4485-9e90-1389a91c0127.png)

**Comment by Yisus7u7** [comment]
DOSBOX currently does not contain direct access (.desktop file)

But you can create direct access by right clicking on the desktop.
