### ISSUE TITLE
stops refereshin

### ISSUE THREAD

**Issue by Alabdullillah** [Yisus7u7/termux-desktop-xfce#110]
when I use the vnc viewer, the screen refreshes normally then.... just stops refreshinb, I can move the cursor around freely, but don't see my interactions with the screen(although the interactions occur, but I can't see them).

**Comment by SUFandom** [comment]
Try using other VNC client

**Comment by flashtechstudios** [comment]
> when I use the vnc viewer, the screen refreshes normally then.... just stops refreshinb, I can move the cursor around freely, but don't see my interactions with the screen(although the interactions occur, but I can't see them).

I would recommend you to use bvnc which is faster and better

**Comment by jynn12** [comment]
> I would recommend you to use bvnc which is faster and better

Nethunter kex also works

**Comment by hyperio546** [comment]
> > I would recommend you to use bvnc which is faster and better
> 
> Nethunter kex also works

Of course it does.

**Comment by Yisus7u7** [comment]
> when I use the vnc viewer, the screen refreshes normally then.... just stops refreshinb, I can move the cursor around freely, but don't see my interactions with the screen(although the interactions occur, but I can't see them).

Can you provide screenshots or a video?

**Comment by SUFandom** [comment]
Tbh this thread is old, probably the op forgor

**Comment by Yisus7u7** [comment]
> Tbh this thread is old, probably the op forgor

Yeah, I better close it because there are no more reports about this, the problem had to be some error in your termux installation or environment.
