### ISSUE TITLE
Brother una pregunta

### ISSUE THREAD

**Issue by XGilmar** [Yisus7u7/termux-desktop-xfce#114]
Donde tienes los ajustes de resolución de pantalla? 
Quiero modificarlo para poderlo ajustar a mi pantalla porque se ve muy pequeña la pantalla cada que la abro gráficamente. Te lo agradecería ✌🏻

**Comment by Yisus7u7** [comment]
Edita el archivo :

`nano ~/.vnc/config`

Y modifica la variable **geometry**, su valor por defecto es 1280x720, si no conoces la resolución de tu celular hay una app de la play store llamada _cpu-z_, dónde encontrarás el valor **geometry**.

Recuerda que el número valor de la resolución va primero y luego el menor, **por ejemplo** si la resolución de tu celular es 820x1630 debería ir esto en el archivo:

`geometry = 1630x820`
