### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by sourcemaster7** [Yisus7u7/termux-desktop-xfce#117]
I connect to it correctly and it just shows a blackscreen. Nothing at all.

**Comment by hyperio546** [comment]
Using android 12 and above by any chance?

**Comment by sourcemaster7** [comment]
no clue

**Comment by hyperio546** [comment]
> no clue
Run
`apt install neofetch -y`
`neofetch`
Send me the output of neofetch

**Comment by hyperio546** [comment]
> no clue

Run:
`apt install neofetch -y`
`neofetch`
Send me the output of neofetch

**Comment by jynn12** [comment]
@sourcemaster7 I also have this problem and I got it fixed. Even if you install the x11-repo, it is not added to the sources.list. Try executing this command
***echo "deb https://packages-cf.termux.dev/apt/termux-x11 x11 main" >> ../usr/etc/apt/sources.list***

After executing that. Run the installer again. If you have any problems, ask away
I hope this helps:)

**Comment by jynn12** [comment]
@Yisus7u7 This issue is solved. You can close this issue now
