### ISSUE TITLE
Failed to run Firefox desktop. Cannot create shortcuts on desktop.

### ISSUE THREAD

**Issue by dextercva** [Yisus7u7/termux-desktop-xfce#119]
I installed Firefox-esr in proot-distro. When I added to desktop by using Launcher. When I double click on this desktop entry. It says the following error.

![Screenshot_2023-02-17-18-36-10-118_com offsec nethunter kex](https://user-images.githubusercontent.com/43370509/219664446-7ea92706-27b5-45b1-a564-cbbf7b25c910.jpg)

But Firefox opens, if I run in terminal.

![Screenshot_2023-02-17-19-19-21-000_com offsec nethunter kex](https://user-images.githubusercontent.com/43370509/219672256-8421e010-a1f5-43f7-8825-5cb478897127.jpg)

I wanna know multiple ways to add/create desktop shortcuts/Launchers. Not only Firefox, even chromium doesn't work. Same error for all other applications added to desktop.

**Comment by Yisus7u7** [comment]
Firefox is available for termux

run:

```bash
pkg install Firefox
```

**Comment by Yisus7u7** [comment]
> Termux apps are running using Desktop shortcuts. I couldn't add Proot apps to desktop. You can see the error in the first image. Not only Firefox, but for all Proot apps. Similar error. `Failed to run "firefox.desktop" GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dexec_2derror_2dquark.Code8: Failed to execute child process "/usr/lib/firefox-esr/firefox-esr" (No such file or directory)`
> 
> Also in VLC media player (Proot app), sound is not playing. How should I get them working?

You are outdated, currently IF you can install firefox and chromium in termux, they work natively, vlc is also available.

´pkg install vlc-qt´

**Comment by dextercva** [comment]
You didn't seem to understand. Anyways, I don't want termux repo apps. I want Ubuntu/debian repo packages. Although, I can download them using proot. Yet couldn't create a shortcut in your desktop-xfce. That's a flaw.

**Comment by Yisus7u7** [comment]
> You didn't seem to understand. Anyways, I don't want termux repo apps. I want Ubuntu/debian repo packages. Although, I can download and run them using proot. Yet couldn't create a shortcut in your desktop-xfce. That's a flaw.

I'm working on it, when I have time I released a tool for that purpose, for now you can use the official termux sources.

```bash
pkg install tur-repo
pkg install Firefox
Or
pkg install chromium

**Comment by Yisus7u7** [comment]
Once I finish the tool to automatically create shortcuts from proot to the desktop I will publish it, for now you will have to settle for the packages from the termux repositories.

Likewise, it will always be better to use packages from the termux repositories since they are compiled and patched in order to take natively on your phone (which means better performance and native compatibility)

**Comment by dextercva** [comment]
Sounds good. Got it. Looking forward to it. Thank you. :)
