### ISSUE TITLE
Some icons on the panel are being weird (circular)

### ISSUE THREAD

**Issue by sharunkumar** [Yisus7u7/termux-desktop-xfce#122]
![image](https://github.com/Yisus7u7/termux-desktop-xfce/assets/715417/b019ba2c-fb08-4f56-98b5-fd4ea9a9c4ac)

Let me know if any additional information is needed

**Comment by Yisus7u7** [comment]
Try in terminal:

xfce4-panel -r

**Comment by sharunkumar** [comment]
> xfce4-panel -r

tried it, still its there

**Comment by 8UA** [comment]
> > xfce4-panel -r
> 
> tried it, still its there

Open a css file in `.config/gtk3.0/gtk.css` with any text editor and find a class named `.xcfe4-panel`, then you'll just need to delete the `border-radius` property.

And lastly refresh the panel by typing
`xfce4-panel -r`.

This solution worked for me.

**Comment by sharunkumar** [comment]
> Open the css file in `.config/gtk3.0/gtk.css` with any text editor and find a class named `.xcfe4-panel`, then you'll just need to delete the `border-radius` property.
> 
> And lastly refresh the panel by typing `xfce4-panel -r`.

works perfectly

@Yisus7u7 any way to make these changes into the repo?

**Comment by Yisus7u7** [comment]
> > Open the css file in `.config/gtk3.0/gtk.css` with any text editor and find a class named `.xcfe4-panel`, then you'll just need to delete the `border-radius` property.
> > And lastly refresh the panel by typing `xfce4-panel -r`.
> 
> works perfectly
> 
> @Yisus7u7 any way to make these changes into the repo?

I will keep it in mind for the next update, I already announced it in the README, it will take me a while since I am the only developer and tester of the project at the same time
