### ISSUE TITLE
I need keep the localhost :1 

### ISSUE THREAD

**Issue by essamkafafy** [Yisus7u7/termux-desktop-xfce#125]
Is very good system and gui but i need help
When after close and re open make new port can see sc attach 
![Screenshot_20230826_094226_Termux](https://github.com/Yisus7u7/termux-desktop-xfce/assets/3779214/529a845a-0d53-47dd-a658-257b54c0d9e2)

And this when running on the localhost:8
![Screenshot_20230826_094208_VNC Viewer](https://github.com/Yisus7u7/termux-desktop-xfce/assets/3779214/25ff2b6d-5605-4243-a49d-dd1c93019b5c)

When after close that and start vncserver make new port for ex localhost : 9

I need keep it localhost : 1

Thanks 🙏🏻

**Comment by Yisus7u7** [comment]
```bash
killall Xvnc

rm -rf $PREFIX/tmp/.X*

vncserver -listen tcp
```
