### ISSUE TITLE
Read only filesystem?

### ISSUE THREAD

**Issue by lexterror** [Yisus7u7/termux-desktop-xfce#126]
Hi Im trying to write to file: nano /etc/mumble-server.ini

it says its a read only filesystem. my phone is not rooted.

thank you!

**Comment by Yisus7u7** [comment]
> Hi Im trying to write to file: nano /etc/mumble-server.ini
> 
> it says its a read only filesystem. my phone is not rooted.
> 
> thank you!

Termux uses a different structure than Linux, if you need to edit that file you should edit it like this:

```bash
nano /data/data/com.termux/files/usr/etc/mumble-server.ini
```

**Comment by lexterror** [comment]
thank you!
