### ISSUE TITLE
Tengo un error en bVNC free

### ISSUE THREAD

**Issue by hectorsamuel** [Yisus7u7/termux-desktop-xfce#16]
El error dice: 'El servidor VNC está intentando utilizar cifrados Diffie Hellman anónimos que no son compatibles con su dispositivo Android. Si utiliza el servidor Vino VNC de GNOME, puede desactivar AnonTLS ejecutando el siguiente comando en una terminal y luego reiniciando: "gsettings set org.gnome.Vino require-encryption false". Si ejecuta x11vnc, puede agregar las siguientes opciones: "- vencrypt nodh: only -ssl".'

**Comment by Yisus7u7** [comment]
Valla a la configuración de esa conexión y donde dice tipo de conexión cambielo a ultra vnc,
Luego de eso debe funcionar

**Comment by hectorsamuel** [comment]
Listo muchas gracias!

**Comment by Yisus7u7** [comment]
De nada
