### ISSUE TITLE
/ permission denied

### ISSUE THREAD

**Issue by mizzunet** [Yisus7u7/termux-desktop-xfce#19]
Does this way has native root(/) or is it sharing Android's own / unlike proof?
I was trying to add a new source to /etc/sources.d however it failed

**Comment by Yisus7u7** [comment]
Those paths do not exist, nor does there exist sudo, this desktop runs 100% natively in termux

**Comment by Yisus7u7** [comment]
All those routes you are looking for are on the termux $PREFIX

**Comment by Yisus7u7** [comment]
> Those paths do not exist, nor does there exist sudo, this desktop runs 100% natively in termux

https://wiki.termux.com/wiki/Graphical_Environment

**Comment by mizzunet** [comment]
@Yisus7u7 thanks 👍🏼

**Comment by mizzunet** [comment]
But I wonder how do I install programs? I tried adding Ubuntu reps to usr/etc/apt/sources.list though `apt update` display error like Release not found etc
And according to Readme, it is done by
./start-ubuntu.sh and install packages, but this file doesn't exist

**Comment by Yisus7u7** [comment]
You are very wrong, that of the readme is an example, AN EXAMPLE, you can use anlinux or andronix to install the distro you want, and please, do not try to add the Ubuntu repositories to Termux, they are different systems and may break the system

**Comment by Yisus7u7** [comment]
@suhan-paradkar Can you explain? ._.

**Comment by mizzunet** [comment]
Oops, noob here :P

**Comment by Yisus7u7** [comment]
I understand, and what do you need from Ubuntu proot that you want to install it?

**Comment by suhan-paradkar** [comment]
> Does this way has native root(/) or is it sharing Android's own / unlike proof?

Termux is a subsystem.... not proot.. not  native root

> I was trying to add a new source to /etc/sources.d however it failed

/etc/sources.d doesn't exist...
use $PREFIX/etc/sources.d

**Comment by mizzunet** [comment]
I don't want anything to install on proot, I'd like to install programs on this DE like firefox. I misunderstood the EXAMPLE you wrote :D

**Comment by mizzunet** [comment]
> /etc/sources.d doesn't exist...
> use $PREFIX/etc/sources.d
Now I know

**Comment by suhan-paradkar** [comment]
> But I wonder how do I install programs? I tried adding Ubuntu reps to usr/etc/apt/sources.list though `apt update` display error like Release not found etc

DO NOT ADD UBUNTU REPOS IN TERMUX
You can do this in proot only....


> And according to Readme, it is done by
> ./start-ubuntu.sh and install packages, but this file doesn't exist

./setup-ubuntu.sh is for building packages in a docker image.... not in native termux....

**Comment by Yisus7u7** [comment]
High, but don't, if you are going to add a repository it must support termux, the repositories should and ubuntu can't use it, it can break your system

**Comment by Yisus7u7** [comment]
An example of a repository that can be used in termux is this : 
https://pkgs-yisus.github.io/pkgs.yisus.org

**Comment by suhan-paradkar** [comment]
> I don't want anything to install on proot, I'd like to install programs on this DE like firefox, I mean natively to termux. And I  misunderstood the EXAMPLE you wrote :D

firefox isn't available natively as of now..

**Comment by mizzunet** [comment]
So,
I cannot install firefox? Firefox shouldn't be supporting termux, however, it has an arm64 build, isn't it?

**Comment by Yisus7u7** [comment]
> @mizzunet
> 
> > ¿De esta manera tiene raíz nativa (/) o está compartiendo la prueba propia / diferente de Android?
> 
> Termux es un subsistema ... no proot ... no es raíz nativa
> 
> > Estaba tratando de agregar una nueva fuente 
> /etc/sources.d no existe ...
 use $PREFIX/etc/apt/source.d/*

**Comment by mizzunet** [comment]
> firefox isn't available natively as of now..

Oh

**Comment by Yisus7u7** [comment]
Firefox to a does not support termux, use this browser as an alternative:  

pkg install otter-browser

**Comment by Yisus7u7** [comment]
If you want to run firefox on termux x11 you will have to emulate it with proot.

**Comment by mizzunet** [comment]
Thanks (:

**Comment by Yisus7u7** [comment]
```
pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
```

```
./start-ubuntu.sh
```

```
apt update ; apt upgrade ; apt install firefox
```
```
export DISPLAY=:1
```

```
firefox
```

**Comment by wildan444** [comment]
root@localhost:~# export DISPLAY=:export DISPLAY=:1
root@localhost:~# firefox
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1

how to fix?

**Comment by wildan444** [comment]
root@localhost:~# export DISPLAY=:export DISPLAY=:1
root@localhost:~# firefox
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1

how to fix?

**Comment by Yisus7u7** [comment]
There will be a normal terminal and enter :

xhost +localhost
xhost +

After that do not close the terminal and follow the steps

**Comment by wildan444** [comment]
where to enter this? 
xhost +localhost 
xhost +

**Comment by Yisus7u7** [comment]
> @Yisus7u7 where to enter this?
> xhost +localhost
> xhost +

Yeah

**Comment by wildan444** [comment]
@Yisus7u7 
where to paste this is "xhost +localhost
xhost +"?

**Comment by Yisus7u7** [comment]
In termux x11

**Comment by wildan444** [comment]
@Yisus7u7 
in .vnc/xstartup ?

**Comment by Yisus7u7** [comment]
No, in the terminal

**Comment by wildan444** [comment]
@Yisus7u7 
~ $ host +localhost
localhost being added to access control list
~ $ xhost +
access control disabled, clients can connect from any host
~ $ ./start-ubuntu.sh
root@localhost:~# export DISPLAY=:1
root@localhost:~# firefox
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1

**Comment by Yisus7u7** [comment]
Before doing that start vncserver with the parameter -listen tcp

**Comment by wildan444** [comment]
@Yisus7u7 
thanks it works 😀
