### ISSUE TITLE
Create English translation of the readme?

### ISSUE THREAD

**Issue by yonderbread** [Yisus7u7/termux-desktop-xfce#2]
Maybe a translated version of the readme could be created for non-spanish speaking users?

**Comment by Yisus7u7** [comment]
Yes, it is possible, I can translate that in the wiki, but termux-desktop-xfce is 100% in English, the only thing in Spanish is the README

**Comment by Yisus7u7** [comment]
README file in English now available

https://github.com/Yisus7u7/termux-desktop-xfce/blob/main/README-en.md

**Comment by yonderbread** [comment]
Alrighty, thank you :)
