### ISSUE TITLE
Run GUI from proot-distro

### ISSUE THREAD

**Issue by mizzunet** [Yisus7u7/termux-desktop-xfce#21]
I installed proot-distro ubuntu 18.04
Then installed firefox into it and ran `export DISPLAY=:1` and `firefox`,
But it returns this
```
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1
```
I tried setting DISPLAY=localhos

**Comment by Yisus7u7** [comment]
Make sure xorg-xhost is working

**Comment by mizzunet** [comment]
May I know how?
```
~ $ xorg-xhost
xorg-xhost: command not found
~ $ xhost
access control disabled, clients can connect from any host
INET:localhost
```

**Comment by Yisus7u7** [comment]
> May I know how?
> 
> ```
> ~ $ xorg-xhost
> xorg-xhost: command not found
> ~ $ xhost
> access control disabled, clients can connect from any host
> INET:localhost
> ```

Enter in a normal terminal : 
```
xhost +localhost 
xhost +
```
And then don't close it, try again to see if firefox if you open it

**Comment by mizzunet** [comment]
![Screenshot_20210705-001127_VNC_Viewer](https://user-images.githubusercontent.com/10193999/124396155-9186ef80-dd25-11eb-8740-29ccdfc1fcbd.png)


Still getting 
![Screenshot_20210705-001123_VNC_Viewer](https://user-images.githubusercontent.com/10193999/124396160-951a7680-dd25-11eb-8770-f225ccc53f07.png)

**Comment by Yisus7u7** [comment]
Also, be sure to aver started vncserver with the -listen tcp parameter

```
vncserver -listen tcp
```
After that follow the steps I just did, and it should work

**Comment by mizzunet** [comment]
That did, thanks mam 🤟

**Comment by mizzunet** [comment]
I'd like to know one more thing, can I run a command inside proot-distro? Something like, single command to open firefox, "proot-distro login ubuntu-18.04 exec firefox"

**Comment by mizzunet** [comment]
For docker container there was "exec" command to execute  commands inside the container, this proot is also like a container, right?

**Comment by Yisus7u7** [comment]
Use this command in a script as an example:
```
proot-distro login ubuntu-18.04 -- firefox
```

**Comment by Yisus7u7** [comment]
Place this in the .bashrc of your Ubuntu : 
`export DISPLAY=:1`

**Comment by mizzunet** [comment]
I have already put that, it does execute "firefox" without export command by manually logging into proot

**Comment by mizzunet** [comment]
But proot-distro login ubuntu-18.04 -- firefox
returns DISPLAY not defined

**Comment by mizzunet** [comment]
Why can't two commands be executed this way?
proot-distro login ubuntu-18.04 -- export DISPLAY=:1&&firefox
or proot-distro login ubuntu-18.04 -- export DISPLAY=:1;firefox

**Comment by Yisus7u7** [comment]
You can only run one at a time, so you must place the export DISPLAY=:1 in the .bashrc

**Comment by mizzunet** [comment]
I have, but still says DISPLAY not specified, however I got it working by setting it in /etc/environment according to this https://stackoverflow.com/questions/13046624/how-to-permanently-export-a-variable-in-linux

**Comment by mizzunet** [comment]
Thanks once again (:

**Comment by layaachmad** [comment]
> ![Screenshot_20210705-001127_VNC_Viewer](https://user-images.githubusercontent.com/10193999/124396155-9186ef80-dd25-11eb-8740-29ccdfc1fcbd.png)
> 
> Still getting
> ![Screenshot_20210705-001123_VNC_Viewer](https://user-images.githubusercontent.com/10193999/124396160-951a7680-dd25-11eb-8770-f225ccc53f07.png)

Try
xhost +
proot-distro login <distro> --shared-tmp
export DISPLAY=:1
firefox

**Comment by Yisus7u7** [comment]
@layaachmad 

You must run the vnc server under this parameter:

`vncserver -listen tcp`

![Screenshot_20210813-182423](https://user-images.githubusercontent.com/64093255/129426800-368f5ee1-5db2-4b2e-821c-fab37df9bce5.png)
