### ISSUE TITLE
Change Transparency

### ISSUE THREAD

**Issue by NoNameMan1231** [Yisus7u7/termux-desktop-xfce#23]
How to change the transparency in termux desktop?

In full transparent mode, I can't watch video with vlc clearly!😕

Here's proof:

![Screenshot_2021_0727_111148](https://user-images.githubusercontent.com/87801676/127089493-0132775b-3e6d-4baa-b87f-fee2caf51f0a.jpg)

**Comment by Yisus7u7** [comment]
That's very rare, but just fence to settings > window manager tweaks, then go to "compositor" and there adjust the transparency to your liking.
