### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by masterjavaofficial** [Yisus7u7/termux-desktop-xfce#24]
Sir, I've installed x11-repo, xfce4 & TigerVNC manually. Now how can I run a GUI app from proot-distro's in Termux's destop environment? Its saying can't open display, connection error etc.. Please note that I didn't use your this repository to install these because I've low memory.

**Comment by Yisus7u7** [comment]
These problems are not reported here, they are reported in the x11 repository of termux, apart, explain in detail what happens to you

**Comment by masterjavaofficial** [comment]
Thanks sir, btw I solved the problem by installing xorg-host and in xstartup script of vnc, ```xhost +localhost && xhost +```
