### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by praveenkumar222** [Yisus7u7/termux-desktop-xfce#26]
After Connect To Vnc 
![Screenshot_20210808-114759](https://user-images.githubusercontent.com/77523501/128622787-6738e560-3c4f-41e9-a0be-82b05bd5ee1e.jpg)
Appears Black Screen Only

**Comment by HidegonSan** [comment]
Me too
![Screenshot_20210808-185812](https://user-images.githubusercontent.com/68275072/128628161-17ef4841-bafd-4565-a16f-a43eb6a7aa03.png)

**Comment by Yisus7u7** [comment]
Try running the installation script again, re-clone the repository, it's up for updating

**Comment by chrisfal10** [comment]
This Is kinda a fix 
https://wiki.termux.com/wiki/Graphical_Environment
