### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by chrisfal10** [Yisus7u7/termux-desktop-xfce#29]
Hi I would first like to thank you from this project 
I tried this project on a fresh installation of termux 
so first I faced some problems
1. no vncserver installed 
2. and vnc server password 
3. > Updating and downloading build scripts...
https://github.com/shpkg/termux-ports.git... done
Error: package dosen't exists in: /data/data/com.termux/files/home/.shpkg
and using get-qt5ct.sh dosent work

solution 
for the vncserver I would like to request u to include it in the installation guide (pkg install tigervnc)
and no password given for the vncserver so I had to manually change using vncpasswd
and the third I have no idea

**Comment by Yisus7u7** [comment]
Thanks, then I do that.
