### ISSUE TITLE
Mate terminal

### ISSUE THREAD

**Issue by praveenkumar222** [Yisus7u7/termux-desktop-xfce#33]
(mate-terminal:21741): GLib-GIO-ERROR **: 18:04:02.706: Settings schema 'org.mate.interface' is not installed
Trap

**Comment by Yisus7u7** [comment]
> (mate-terminal:21741): GLib-GIO-ERROR **: 18:04:02.706: Settings schema 'org.mate.interface' is not installed
> Trap

Run :  
`pkg install mate-settings-daemon`

After that mate-terminal will work without problems
