### ISSUE TITLE
Don't have terminal

### ISSUE THREAD

**Issue by FuzzByte** [Yisus7u7/termux-desktop-xfce#34]
Do the setup installed a xfce terminal? I can't seem to find 
![Screenshot_2021-09-13-18-40-54-330_com realvnc viewer android](https://user-images.githubusercontent.com/59109346/133070008-776e9329-c4ff-428b-88c0-0f07337d8970.jpg)

**Comment by Yisus7u7** [comment]
Run : 

`pkg install xfce4-terminal`

**Comment by layaachmad** [comment]
> Do the setup installed a xfce terminal? I can't seem to find 
> ![Screenshot_2021-09-13-18-40-54-330_com realvnc viewer android](https://user-images.githubusercontent.com/59109346/133070008-776e9329-c4ff-428b-88c0-0f07337d8970.jpg)
> 

It just that incorrectly installed

**Comment by Yisus7u7** [comment]
That happens when the connection fails and the download of the packages goes down. 

It has happened to others before.
