### ISSUE TITLE
Can't ran proot-distro apps

### ISSUE THREAD

**Issue by NoNameMan1231** [Yisus7u7/termux-desktop-xfce#37]
I tried to run chromium browser but can't ran.
It  just gave me 'unable to init server :(

https://user-images.githubusercontent.com/87801676/135008723-68754d75-1b8a-489d-877d-e767e051b8d7.mp4

**Comment by Yisus7u7** [comment]
the server must be running listening for tcp connections.

`vncserver -listen tcp`

**Comment by JyanJohn** [comment]
@Yisus7u7 yea but still same error

**Comment by JyanJohn** [comment]
@Yisus7u7 nevermind #21 solved the problem


┌──(jyanjohn㉿termux)-[~]
└─$ xhost +
access control disabled, clients can connect from any host
┌──(jyanjohn㉿termux)-[~]
└─$ proot-distro login ubuntu --shared-tmp
root@localhost:~# export DISPLAY=:1
root@localhost:~# firefox
