### ISSUE TITLE
Always connecting in VNC Viewer or desktop not responding

### ISSUE THREAD

**Issue by EvoLandEco** [Yisus7u7/termux-desktop-xfce#38]
![Screenshot_20210930_070254_com realvnc viewer android](https://user-images.githubusercontent.com/57348932/135390526-bb06bb6d-65a2-4eb0-85cb-63145556d74d.jpg)
I tried the desktop with no problem at the beginning, but when I try it later, it is always connecting but cannot proceed after I typed in my password.

If I kill the vncserver and start it again, I maybe login in successfully but the desktop is not responding, I can't click on any buttons on the desktop

**Comment by Yisus7u7** [comment]
Before returning to the vnc server you must run :  

```bash
killall Xvnc

vncserver -listen tcp
```

**Comment by EvoLandEco** [comment]
This works for me, thanks
