### ISSUE TITLE
Getting Black Screen.

### ISSUE THREAD

**Issue by HyperNotAryanX97** [Yisus7u7/termux-desktop-xfce#4]
Am using A10.
Aarch64.
![Screenshot_20210520-103610515](https://user-images.githubusercontent.com/66762638/118922227-483a3680-b957-11eb-81be-31a826e6f7ab.jpg)

**Comment by Yisus7u7** [comment]
It may be that the installation of your dependencies was shutting up during installation and you did not notice, run the installation script again, I will work on scripting for situations like these

**Comment by Yisus7u7** [comment]
Is the termux you use from the play store?

**Comment by HyperNotAryanX97** [comment]
> Is the termux you use from the play store?

Noo Actually am using termux from f-droid.

**Comment by HyperNotAryanX97** [comment]
> It may be that the installation of your dependencies was shutting up during installation and you did not notice, run the installation script again, I will work on scripting for situations like these

Yeah maybe it would work.

**Comment by Yisus7u7** [comment]
Well, for the moment run the installation script again, if it is not resolved please let me know

**Comment by HyperNotAryanX97** [comment]
> Well, for the moment run the installation script again, if it is not resolved please let me know

Yes running the script again fixes the error. Thanks.
