### ISSUE TITLE
terminal not working

### ISSUE THREAD

**Issue by devshahoriar** [Yisus7u7/termux-desktop-xfce#46]
![Screenshot_2021-10-30-09-26-57-819_com realvnc viewer android](https://user-images.githubusercontent.com/76418496/139518727-9b9302b7-02b8-436f-ab79-ca7bd00fc716.jpg)

**Comment by Learn-Termux** [comment]
Run 👍 
```
pkg in xfce4*```

**Comment by Yisus7u7** [comment]
You must select the terminal to use, in the case select "xfce4-terminal"
