### ISSUE TITLE
terminal crashes vnc

### ISSUE THREAD

**Issue by 12brendon34** [Yisus7u7/termux-desktop-xfce#5]
when i open a terminal window vnc closes and i need to start a new one

**Comment by Yisus7u7** [comment]
Can you tell me the features of your device?, Android version, architecture, termux app version, ram memory charity and space

**Comment by 12brendon34** [comment]
> Can you tell me the features of your device?, Android version, architecture, termux app version, ram memory charity and space
![Screenshot_20210520-121120_CPU-Z](https://user-images.githubusercontent.com/43822289/119035610-9ace1f80-b964-11eb-8a20-8dcc23b710c8.jpg)
![Screenshot_20210520-121120_CPU-Z](https://user-images.githubusercontent.com/43822289/119035634-a0c40080-b964-11eb-94d2-b5a772da5393.jpg)

**Comment by 12brendon34** [comment]
https://user-images.githubusercontent.com/43822289/119037251-94d93e00-b966-11eb-8042-b55602e6667d.mp4

**Comment by Yisus7u7** [comment]
Please, could you upload the log of your session vnc to see the error?, and also, the termux you use is from the play store?

**Comment by Yisus7u7** [comment]
If you're using the play store termux, that may be the problem

**Comment by 12brendon34** [comment]
I'm not using the play store version but I found it's not your fault

Basically it will crash vnc if you remove the /home/.vnc/localhost:1.pid file because it doesn't actually kill the session

I have no idea why the terminal window crashes it but It doesn't matter

**Comment by 12brendon34** [comment]
Thanks for responding verry fast btw

**Comment by Yisus7u7** [comment]
Oh well, then you finally fixed it?
