### ISSUE TITLE
Update and Upgrade

### ISSUE THREAD

**Issue by JyanJohn** [Yisus7u7/termux-desktop-xfce#50]
Please remove the automatic update and upgrade in the installer, I have lots of stuff installed in termux and I dont wanna upgrade because its gonna break some stuff, you should add a "Would you like to upgrade [Y/n]" option.

**Comment by Yisus7u7** [comment]
Hmmm

**Comment by Yisus7u7** [comment]
Termux has already solved everything, nothing will be broken.
