### ISSUE TITLE
VNC Problem

### ISSUE THREAD

**Issue by JyanJohn** [Yisus7u7/termux-desktop-xfce#51]
Here is the full error, I also tried vncserver -listen tcp

┌──(jyanjohn@termux)-[~]
└─$ startdesktop                                                    

New 'localhost:1 ()' desktop is localhost:1

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:1.log

I tried to connect and it says connection unexpectedly closed so I killed the vnc server but its already killed

┌──(jyanjohn@termux)-[~]
└─$ vncserver -kill :1                                                       
Killing Xvnc process ID 8133
Xvnc process ID 8133 already killed

**Comment by Yisus7u7** [comment]
killall Xvnc

vncserver -listen tcp

**Comment by JyanJohn** [comment]
Can you suggest a vnc viewer? Whenever I try to connect to vnc it says these 

VNC Viewer
"Connection unexpectedly closed"

bVNC and Nethunter KeX
"The VNC Server is trying to use Diffie Hellman ciphers which are not supported by your device"

- - - - - - - - - - - - - - - - - - - - - - - - - 
┌──(jyanjohn@termux)-[~]
└─$ killall Xvnc                                           
Xvnc: no process found
┌──(jyanjohn@termux)-[~]
└─$ vncserver -listen tcp                                   

New 'localhost:1 ()' desktop is localhost:1

Starting applications specified in /data/data/com.termux/files/home/.vnc/xstartup
Log file is /data/data/com.termux/files/home/.vnc/localhost:1.log

┌──(jyanjohn@termux)-[~]
└─$ killall Xvnc                                            
Xvnc: no process found
┌──(jyanjohn@termux)-[~]
└─$ vncserver -kill :1                                     
Killing Xvnc process ID 18534
Xvnc process ID 18534 already killed
┌──(jyanjohn@termux)-[~]
└─$

**Comment by Yisus7u7** [comment]
It's already working, just connect to localhost:5901 in vnc viewer or bvnc

**Comment by JyanJohn** [comment]
Same error

**Comment by JyanJohn** [comment]
Connection closed unexpectedly

**Comment by Yisus7u7** [comment]
What version of termux do you have installed?

**Comment by JyanJohn** [comment]
Latest from F-Droid

**Comment by Yisus7u7** [comment]
You can provide me with the contents of the file `~/.vnc/localhost:1.log` ?

**Comment by JyanJohn** [comment]
oki

**Comment by JyanJohn** [comment]
┌──(jyanjohn@termux)-[~]
└─$ cat .vnc/localhost:1.log                               
InitConnectionLimits: MaxClients = 2048

Xvnc TigerVNC 1.10.0 - built Oct 25 2021 14:10:56
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12000000, The X.Org Foundation


Fri Nov  5 09:40:02 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
Sync Extension 3.1
Popen: `"/data/data/com.termux/files/usr/bin/xkbcomp" -w 1 "-R/data/data/com.termux/files/usr/share/X11/xkb" -xkm "-" -em1 "The XKEYBOARD keymap compiler (xkbcomp) reports:" -emp "> " -eml "Errors from xkbcomp are not fatal to the X server" "/data/data/com.termux/files/usr/tmp/server-1.xkm"', fp = 0x7231534018
Pclose: fp = 0x7231534018
Loaded XKB keymap /data/data/com.termux/files/usr/tmp/server-1.xkm, defined=0x7f
client(0): Reserved pid(22331).
client(0): Reserved cmdname(/data/data/com.termux/files/usr/bin/Xvnc) and cmdargs(:1 -auth /data/data/com.termux/files/home/.Xauthority -desktop localhost:1 () -fp /data/data/com.termux/files/usr/share/fonts/75dpi -geometry 1024x768 -pn -rfbauth /data/data/com.termux/files/home/.vnc/passwd -rfbport 5901 -rfbwait 30000 -listen tcp).
/data/data/com.termux/files/home/.vnc/xstartup: 11: twm: not found
client(200000): Reserved pid(22338).
client(200000): Reserved cmdname(aterm) and cmdargs(-geometry 80x24+10+10 -ls).
AllocNewConnection: client index = 1, socket fd = 10
aterm: Failed to open input method

Fri Nov  5 09:40:10 2021
 Connections: accepted: 127.0.0.1::47222
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
terminating with uncaught exception of type rdr::Exception
(EE)
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
X connection to :1 broken (explicit kill or server shutdown).
┌──(jyanjohn@termux)-[~]
└─$

**Comment by Yisus7u7** [comment]
Please give me the output of the following command : `termux-info`

Also check if you have packages to update `apt update && apt upgrade`

**Comment by JyanJohn** [comment]
┌──(jyanjohn@termux)-[~]
└─$ termux-info                                             
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/gushmazuko.list
deb https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
adwaita-icon-theme/x11 40.1.1-1 all [upgradable from: 40.1.1]
apache2/stable 1:2.4.51 aarch64 [upgradable from: 1:2.4.49-1]
apr/stable 1.7.0-5 aarch64 [upgradable from: 1.7.0-4]
apt/stable 2.3.11-4 aarch64 [upgradable from: 2.3.9]
aterm/x11 1.0.1-33 aarch64 [upgradable from: 1.0.1-32]
atk/x11 2.36.0-11 aarch64 [upgradable from: 2.36.0-10]
binutils/stable 2.37-3 aarch64 [upgradable from: 2.37-1]
bison/stable 3.8.2 aarch64 [upgradable from: 3.8.1]
c-ares/stable 1.18.1 aarch64 [upgradable from: 1.17.2]
ca-certificates/stable 1:2021-10-26-0 all [upgradable from: 20211001]
calc/stable 2.13.0.1-1 aarch64 [upgradable from: 2.13.0.1]
calcurse-caldav/stable 4.7.1-3 aarch64 [upgradable from: 4.7.1-1]
calcurse/stable 4.7.1-3 aarch64 [upgradable from: 4.7.1-1]
clang/stable 13.0.0-1 aarch64 [upgradable from: 12.0.1]
command-not-found/stable 1.66 aarch64 [upgradable from: 1.63]
coreutils/stable 9.0 aarch64 [upgradable from: 8.32-8]
debianutils/stable 5.5 aarch64 [upgradable from: 4.11.2]
desktop-file-utils/x11 0.26-6 aarch64 [upgradable from: 0.26-5]
ed/stable 1.17-4 aarch64 [upgradable from: 1.17]
elinks/stable 0.14.3 aarch64 [upgradable from: 0.13.GIT-7]
fltk/x11 1.3.7-1 aarch64 [upgradable from: 1.3.7]
gdbm/stable 1.21-2 aarch64 [upgradable from: 1.20]
gh/stable 2.2.0 aarch64 [upgradable from: 2.0.0]
git/stable 2.33.1 aarch64 [upgradable from: 2.33.0-1]
glu/x11 9.0.2-1 aarch64 [upgradable from: 9.0.2]
gtk-update-icon-cache/x11 3.24.24-5 aarch64 [upgradable from: 3.24.24-4]
gtk3/x11 3.24.24-5 aarch64 [upgradable from: 3.24.24-4]
harfbuzz/stable 3.1.0 aarch64 [upgradable from: 3.0.0]
hicolor-icon-theme/x11 0.17-28 all [upgradable from: 0.17-27]
libc++/stable 23b-3 aarch64 [upgradable from: 21d-1]
libcaca/stable 0.99.beta19-9 aarch64 [upgradable from: 0.99.beta19-8]
libdrm/x11 2.4.107-1 aarch64 [upgradable from: 2.4.107]
libepoxy/x11 1.5.8-1 aarch64 [upgradable from: 1.5.8]
libflac/stable 1.3.3-2 aarch64 [upgradable from: 1.3.3-1]
libfontenc/x11 1.1.4-21 aarch64 [upgradable from: 1.1.4-20]
libgd/stable 1:2.3.3 aarch64 [upgradable from: 2.3.3-1]
libgraphite/stable 1.3.14-1 aarch64 [upgradable from: 1.3.14]
libgrpc/stable 1.38.1-1 aarch64 [upgradable from: 1.38.1]
libicu/stable 70.1 aarch64 [upgradable from: 69.1]
libllvm/stable 13.0.0-1 aarch64 [upgradable from: 12.0.1]
libnghttp2/stable 1.46.0 aarch64 [upgradable from: 1.45.1]
libnl/stable 3.5.0-1 aarch64 [upgradable from: 3.5.0]
libprotobuf/stable 2:3.19.1 aarch64 [upgradable from: 2:3.18.0]
libtiff/stable 4.3.0-1 aarch64 [upgradable from: 4.3.0]
libtirpc/stable 1.3.1-2 aarch64 [upgradable from: 1.3.1]
libx11/stable 1.7.2-1 aarch64 [upgradable from: 1.7.2]
libxcomposite/x11 0.4.5-20 aarch64 [upgradable from: 0.4.5-19]
libxdamage/x11 1.1.5-19 aarch64 [upgradable from: 1.1.5-18]
libxfont2/x11 2.0.5-1 aarch64 [upgradable from: 2.0.5]
libxinerama/x11 1.1.4-25 aarch64 [upgradable from: 1.1.4-24]
libxkbfile/x11 1.1.0-22 aarch64 [upgradable from: 1.1.0-21]
libxml2/stable 2.9.12-1 aarch64 [upgradable from: 2.9.12]
libxmu/x11 1.1.3-23 aarch64 [upgradable from: 1.1.3-22]
libxshmfence/x11 1.3-29 aarch64 [upgradable from: 1.3-28]
libxxf86vm/x11 1.1.4-30 aarch64 [upgradable from: 1.1.4-29]
m4/stable 1.4.19-1 aarch64 [upgradable from: 1.4.19]
mariadb/stable 2:10.6.4-4 aarch64 [upgradable from: 2:10.6.4]
nano/stable 5.9 aarch64 [upgradable from: 5.8]
ncurses-ui-libs/stable 6.2.20200725-6 aarch64 [upgradable from: 6.2.20200725-5]
ncurses-utils/stable 6.2.20200725-6 aarch64 [upgradable from: 6.2.20200725-5]
ncurses/stable 6.2.20200725-6 aarch64 [upgradable from: 6.2.20200725-5]
ndk-sysroot/stable 23b aarch64 [upgradable from: 21d-2]
nmap-ncat/stable 7.91-3 aarch64 [upgradable from: 7.91-1]
nmap/stable 7.91-3 aarch64 [upgradable from: 7.91-1]
openssh/stable 8.8p1 aarch64 [upgradable from: 8.7p1]
patchelf/stable 0.13-1 aarch64 [upgradable from: 0.13]
pcre2/stable 10.39 aarch64 [upgradable from: 10.37]
perl/stable 5.34.0-2 aarch64 [upgradable from: 5.34.0]
php/stable 8.0.6-7 aarch64 [upgradable from: 8.0.6-2]
postgresql/stable 13.3-1 aarch64 [upgradable from: 13.3]
proot-distro/stable 2.8.0 all [upgradable from: 2.6.2]
proot/stable 5.1.107-49 aarch64 [upgradable from: 5.1.107-44]
protobuf/stable 2:3.19.1 aarch64 [upgradable from: 2:3.18.0]
pv/stable 1.6.20 aarch64 [upgradable from: 1.6.6]
python/stable 3.10.0-3 aarch64 [upgradable from: 3.9.7]
shared-mime-info/x11 2.1-3 aarch64 [upgradable from: 2.1-2]
termux-elf-cleaner/stable 1.10 aarch64 [upgradable from: 1.7]
termux-tools/stable 0.149 all [upgradable from: 0.140]
tor/stable 0.4.6.7-3 aarch64 [upgradable from: 0.4.6.6-3]
vim-runtime/stable 8.2.3500-2 all [upgradable from: 8.2.2800-1]
vim/stable 8.2.3500-2 aarch64 [upgradable from: 8.2.2800-1]
wireshark-gtk/x11 2.6.14-18 aarch64 [upgradable from: 2.6.14-17]
xkeyboard-config/x11 2.32-2 all [upgradable from: 2.32-1]
xorg-font-util/x11 1.3.2-21 aarch64 [upgradable from: 1.3.2-20]
xorg-fonts-75dpi/x11 1.0.3-26 all [upgradable from: 1.0.3-25]
xorg-fonts-alias/x11 1.0.4-4 all [upgradable from: 1.0.4-3]
xorg-fonts-encodings/x11 1.0.5-23 all [upgradable from: 1.0.5-22]
xorg-mkfontscale/x11 1.2.1-23 aarch64 [upgradable from: 1.2.1-22]
xorg-xauth/x11 1.1-22 aarch64 [upgradable from: 1.1-21]
xorg-xkbcomp/x11 1.4.5-2 aarch64 [upgradable from: 1.4.5-1]
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Sat Oct 9 16:32:16 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1906
┌──(jyanjohn@termux)-[~]
└─$

**Comment by Yisus7u7** [comment]
Please update your packages, you have many undated packages, some must be broken.

**Comment by JyanJohn** [comment]
ok

**Comment by JyanJohn** [comment]
@Yisus7u7 I finally got it running, but how do I make the windows transparent?

**Comment by Yisus7u7** [comment]
> @Yisus7u7 I finally got it running, but how do I make the windows transparent?

Go to settings > window manager tweaks > compositor

**Comment by JyanJohn** [comment]
Thanks! BTW I used your Hydra-in-termux script 

https://github.com/jyanjohn/PisoWifi-BruteForce
