### ISSUE TITLE
How to open it again

### ISSUE THREAD

**Issue by DISLIKE-99** [Yisus7u7/termux-desktop-xfce#55]
Hi sir..
One i close this from VNC VIEWER it says 
THE PORT ON WHICH COMPUTER IS LISTING
FOR A CONNECTION COULD NOT BE CONTACTED how can i solve this?

**Comment by Yisus7u7** [comment]
> Hi sir.. One i close this from VNC VIEWER it says THE PORT ON WHICH COMPUTER IS LISTING FOR A CONNECTION COULD NOT BE CONTACTED how can i solve this?

`killall Xvnc`

`vncserver -listen tcp`

**Comment by DISLIKE-99** [comment]
Ok thanks it work

But i want to replace this with new vnc server how can i do that?

**Comment by DISLIKE-99** [comment]
How can i install chrome or any other browser in this file can u tell me the cmds? Pls..

**Comment by Yisus7u7** [comment]
You can install netsurf or otter-browser

**Comment by DISLIKE-99** [comment]
Can u give cmds for netsurf or otter - browser?

**Comment by praveenkumar222** [comment]
> Can u give cmds for netsurf or otter - browser?

``` pkg in otter-browser ```
