### ISSUE TITLE
black screen when running with root

### ISSUE THREAD

**Issue by Zeyrox1090** [Yisus7u7/termux-desktop-xfce#62]
heres the log
[localhost:1.log](https://github.com/Yisus7u7/termux-desktop-xfce/files/7633120/localhost.1.log)

**Comment by Zeyrox1090** [comment]
fixed i went through closed issues

**Comment by Zeyrox1090** [comment]
running it with root makes it also black screen
[localhost:1.log](https://github.com/Yisus7u7/termux-desktop-xfce/files/7633332/localhost.1.log)

**Comment by Zeyrox1090** [comment]
![Screenshot_2021-12-01-19-24-34-80_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/73925046/144226336-d2cedbd7-f980-483f-9064-40c11558c87a.jpg)

**Comment by Yisus7u7** [comment]
The use of root is not supported, termux was designed to be used without root, therefore many things will not work if you use the root user
