### ISSUE TITLE
Every vnc server auto kill after some time.why???

### ISSUE THREAD

**Issue by MRJ-Badshah** [Yisus7u7/termux-desktop-xfce#68]
![IMG_20211218_212113](https://user-images.githubusercontent.com/69976020/146647162-f6d70ab6-5ed6-42e0-84dc-6b3d46cf6b4b.jpg)
Every vnc server kill after some time.why????????

**Comment by Yisus7u7** [comment]
Send me the contents of `~/.vnc/localhost:1.log`

**Comment by MRJ-Badshah** [comment]
This 
`InitConnectionLimits: MaxClients = 2048

Xvnc TigerVNC 1.10.0 - built Oct 25 2021 14:10:56
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12000000, The X.Org Foundation


Sat Dec 18 22:00:28 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
Sync Extension 3.1
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/misc/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/TTF/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/OTF/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/Type1/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/100dpi/, removing from list!
[dix] Could not init font path element /data/data/com.termux/files/usr/share/fonts/75dpi/, removing from list!
Popen: `"/data/data/com.termux/files/usr/bin/xkbcomp" -w 1 "-R/data/data/com.termux/files/usr/share/X11/xkb" -xkm "-" -em1 "The XKEYBOARD keymap compiler (xkbcomp) reports:" -emp "> " -eml "Errors from xkbcomp are not fatal to the X server" "/data/data/com.termux/files/usr/tmp/server-1.xkm"', fp = 0x7fb000c018
Pclose: fp = 0x7fb000c018
Loaded XKB keymap /data/data/com.termux/files/usr/tmp/server-1.xkm, defined=0x7f
client(0): Reserved pid(5398).
client(0): Reserved cmdname(/data/data/com.termux/files/usr/bin/Xvnc) and cmdargs(:1 -auth /data/data/com.termux/files/home/.Xauthority -desktop localhost:1 () -geometry 1024x768 -pn -rfbauth /data/data/com.termux/files/home/.vnc/passwd -rfbport 5901 -rfbwait 30000 -listen tcp).
client(200000): Reserved pid(5432).
client(200000): Reserved cmdname(xhost) and cmdargs(+).
AllocNewConnection: client index = 1, socket fd = 10
access control disabled, clients can connect from any host
client(200000): Released pid(5432).
client(200000): Released cmdline(xhost) and cmdargs(+).
client(200000): Reserved pid(5431).
client(200000): Reserved cmdname(/data/data/com.termux/files/usr/bin/dbus-launch) and cmdargs(--sh-syntax --exit-with-session xfce4-session).
AllocNewConnection: client index = 1, socket fd = 10
client(400000): Reserved pid(5437).
client(400000): Reserved cmdname(/data/data/com.termux/files/usr/bin/dbus-launch) and cmdargs(--sh-syntax --exit-with-session xfce4-session).
AllocNewConnection: client index = 2, socket fd = 11
client(600000): Reserved pid(5431).
client(600000): Reserved cmdname(xfce4-session) and cmdargs(NULL).
AllocNewConnection: client index = 3, socket fd = 12
xfce4-session: No SSH authentication agent found
client(800000): Reserved pid(5450).
client(800000): Reserved cmdname(xfwm4) and cmdargs(NULL).
AllocNewConnection: client index = 4, socket fd = 13

(xfwm4:5450): xfwm4-WARNING **: 22:00:32.951: Cannot find a matching visual for the frame buffer config.

(xfwm4:5450): xfwm4-WARNING **: 22:00:32.952: Cannot find a matching GLX config, vsync disabled.
client(a00000): Reserved pid(5457).
client(a00000): Reserved cmdname(xfsettingsd) and cmdargs(NULL).
AllocNewConnection: client index = 5, socket fd = 15
client(c00000): Reserved pid(5457).
client(c00000): Reserved cmdname(xfsettingsd) and cmdargs(NULL).
AllocNewConnection: client index = 6, socket fd = 18
client(c00000): Released pid(5457).
client(c00000): Released cmdline(xfsettingsd) and cmdargs(NULL).

Sat Dec 18 22:00:33 2021
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)

(xfsettingsd:5457): xfsettingsd-CRITICAL **: 22:00:33.289: Failed to apply display settings
client(c00000): Reserved pid(5457).
client(c00000): Reserved cmdname(xfsettingsd) and cmdargs(NULL).
AllocNewConnection: client index = 6, socket fd = 18
client(e00000): Reserved pid(5460).
client(e00000): Reserved cmdname(xfce4-panel) and cmdargs(NULL).
AllocNewConnection: client index = 7, socket fd = 19
client(1000000): Reserved pid(5460).
client(1000000): Reserved cmdname(xfce4-panel) and cmdargs(NULL).
AllocNewConnection: client index = 8, socket fd = 20
client(1000000): Released pid(5460).
client(1000000): Released cmdline(xfce4-panel) and cmdargs(NULL).
client(1000000): Reserved pid(5465).
client(1000000): Reserved cmdname(Thunar) and cmdargs(--daemon).
AllocNewConnection: client index = 8, socket fd = 20
client(c00000): Released pid(5457).
client(c00000): Released cmdline(xfsettingsd) and cmdargs(NULL).
client(c00000): Reserved pid(5470).
client(c00000): Reserved cmdname(xfdesktop) and cmdargs(NULL).
AllocNewConnection: client index = 6, socket fd = 18
client(1200000): Reserved pid(5470).
client(1200000): Reserved cmdname(xfdesktop) and cmdargs(NULL).
AllocNewConnection: client index = 9, socket fd = 21
client(1400000): Reserved pid(5473).
client(1400000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libwhiskermenu.so 1 14680071 whiskermenu Whisker Menu Show a menu to easily access installed applications).
AllocNewConnection: client index = 10, socket fd = 22

(xfce4-session:5431): xfce4-session-WARNING **: 22:00:37.174: Unable to launch "export QT_QPA_PLATFORMTHEME=qt5ct" (specified by autostart/qt5ct theme engine.desktop): Failed to execute child process “export” (No such file or directory)

(xfce4-session:5431): xfce4-session-WARNING **: 22:00:37.182: Unable to launch "play /data/data/com.termux/files/usr/share/sounds/freedesktop/stereo/service-login.oga" (specified by autostart/Login Sound.desktop): Failed to execute child process “play” (No such file or directory)
client(1600000): Reserved pid(5482).
client(1600000): Reserved cmdname(xfsettingsd) and cmdargs(NULL).
AllocNewConnection: client index = 11, socket fd = 23
client(1800000): Reserved pid(5483).
client(1800000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/notifyd/xfce4-notifyd) and cmdargs(NULL).
AllocNewConnection: client index = 12, socket fd = 26
client(1a00000): Reserved pid(5486).
client(1a00000): Reserved cmdname(xfce4-screensaver) and cmdargs(NULL).
AllocNewConnection: client index = 13, socket fd = 27
client(1600000): Released pid(5482).
client(1600000): Released cmdline(xfsettingsd) and cmdargs(NULL).

** (xfdesktop:5470): WARNING **: 22:00:37.637: Failed to get system bus: Could not connect: No such file or directory
libpager-Message: 22:00:40.173: Setting the pager rows returned false. Maybe the setting is not applied.
client(1600000): Reserved pid(5516).
client(1600000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libclipman.so 19 14680073 xfce4-clipman-plugin Clipman Clipboard manager).
AllocNewConnection: client index = 11, socket fd = 23
client(1c00000): Reserved pid(5521).
client(1c00000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libnotification-plugin.so 10 14680075 notification-plugin Notification Plugin Notification plugin for the Xfce panel).
AllocNewConnection: client index = 14, socket fd = 28
client(1e00000): Reserved pid(5520).
client(1e00000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libsystray.so 6 14680074 systray Status Tray Plugin Provides status notifier items (application indicators) and legacy systray items).
AllocNewConnection: client index = 15, socket fd = 29
client(2000000): Reserved pid(5529).
client(2000000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libwavelan.so 20 14680076 wavelan Wavelan View the status of a wireless network).
AllocNewConnection: client index = 16, socket fd = 30
client(2200000): Reserved pid(5545).
client(2200000): Reserved cmdname(/data/data/com.termux/files/usr/lib/xfce4/panel/wrapper-2.0) and cmdargs(/data/data/com.termux/files/usr/lib/xfce4/panel/plugins/libactions.so 14 14680077 actions Action Buttons Log out, lock or other system actions).
AllocNewConnection: client index = 17, socket fd = 31

(wrapper-2.0:5521): GLib-GIO-CRITICAL **: 22:00:47.023: g_file_new_for_path: assertion 'path != NULL' failed

(wrapper-2.0:5521): GLib-GIO-CRITICAL **: 22:00:47.023: g_file_monitor_file: assertion 'G_IS_FILE (file)' failed

(wrapper-2.0:5521): GLib-GObject-WARNING **: 22:00:47.023: invalid (NULL) pointer instance

(wrapper-2.0:5521): GLib-GObject-CRITICAL **: 22:00:47.023: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:5521): Gtk-WARNING **: 22:00:47.024: Attempting to add a widget with type GtkToggleButton to a container of type XfcePanelPlugin, but the widget is already inside a container of type XfcePanelPlugin, please remove the widget from its existing container first.

(wrapper-2.0:5516): Gtk-WARNING **: 22:00:47.981: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

(wrapper-2.0:5529): Gtk-WARNING **: 22:00:47.985: gtk_widget_size_allocate(): attempt to allocate widget with width -3 and height 28

(wrapper-2.0:5521): Gtk-WARNING **: 22:00:48.098: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)

(xfce4-session:5431): xfce4-session-WARNING **: 22:00:48.225: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:5431): xfce4-session-WARNING **: 22:00:48.237: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:5431): xfce4-session-WARNING **: 22:00:48.268: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(wrapper-2.0:5473): Gtk-WARNING **: 22:00:48.683: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)
Xlib:  extension "DPMS" missing on display ":1.0".`

**Comment by Yisus7u7** [comment]
It's strange, I don't see any mistakes.

Try:

```bash
rm -rf ~/.vnc/*pid*

rm -rf ~/.vnc/passwd

killall Xvnc

vnvserver -listen tcp
```

**Comment by MRJ-Badshah** [comment]
![IMG_20211218_221304](https://user-images.githubusercontent.com/69976020/146648865-156b1e38-6d36-4710-ba3c-c47087ebb1a7.jpg)
```A new problem```

**Comment by MRJ-Badshah** [comment]
After that

**Comment by Yisus7u7** [comment]
> ![IMG_20211218_221304](https://user-images.githubusercontent.com/69976020/146648865-156b1e38-6d36-4710-ba3c-c47087ebb1a7.jpg) `A new problem`

vncserver*

**Comment by MRJ-Badshah** [comment]
What your mean I couldn't understand

**Comment by matthewjberger** [comment]
> What your mean I couldn't understand

You had misspelled 'vncserver' as 'vnvserver'
