### ISSUE TITLE
Parole player fails to play music.

### ISSUE THREAD

**Issue by Anonymous2716** [Yisus7u7/termux-desktop-xfce#70]
Parole player needs QuickTime demuxer . How do I install?

**Comment by Yisus7u7** [comment]
> Parole player needs QuickTime demuxer . How do I install?

It should work, in case it doesn't work, install the gst-libav package

**Comment by Anonymous2716** [comment]
Already installed. First it says need codec then tries to install plugin but fails. And I have all dependencies installed that are parole related.
