### ISSUE TITLE
How do I install Firefox

### ISSUE THREAD

**Issue by Coolpowersearch** [Yisus7u7/termux-desktop-xfce#72]
I tried to download the compressed package on Firefox's official website, but it didn't work, and otter-browser was a little difficult to use.Can I install firefox?

**Comment by Yisus7u7** [comment]
> I tried to download the compressed package on Firefox's official website, but it didn't work, and otter-browser was a little difficult to use.Can I install firefox?

Unfortunately firefox does not support termux x11 currently, but you can emulate it with proot.
