### ISSUE TITLE
Needs root ?

### ISSUE THREAD

**Issue by AKPR2007** [Yisus7u7/termux-desktop-xfce#75]
You know the drill

Also is there a video tutorial. I feel like this version is liter than termux desktop by adi

**Comment by Yisus7u7** [comment]
> You know the drill
> 
> Also is there a video tutorial. I feel like this version is liter than termux desktop by adi

No, no root needed.

**Comment by Aridlvory** [comment]
> You know the drill
> 
> Also is there a video tutorial. I feel like this version is liter than termux desktop by adi

Yeah lighter, faster, efficient and multipurpose
You got everything in this
