### ISSUE TITLE
One command only

### ISSUE THREAD

**Issue by AKPR2007** [Yisus7u7/termux-desktop-xfce#76]
Wait. Do I only need to enter the one command directly from readme.md or do I need to at first prepare the environment then do it ?? Like install termux API first

**Comment by Yisus7u7** [comment]
> Wait. Do I only need to enter the one command directly from readme.md or do I need to at first prepare the environment then do it ?? Like install termux API first

You only have to enter the readme command, although if you want to install termux-api you can do it, to get connection status in termux-desktop-xfce

**Comment by AKPR2007** [comment]
Ok
