### ISSUE TITLE
Have a black screen.

### ISSUE THREAD

**Issue by Coolpowersearch** [Yisus7u7/termux-desktop-xfce#77]
When I execute the installation command, he prompts these (as shown), and the black screen is displayed after the connection, what should I do?
![Uploading Screenshot_2022-01-14-00-08-16-850_com.termux.jpg…]()

**Comment by AKPR2007** [comment]
Can't see the screenshot

**Comment by JyanJohn** [comment]
apt install dbus dbus-x11

**Comment by Yisus7u7** [comment]
These problems happen when you have an unstable connection to the Internet, some packages may not have been installed, try running the script again. 

delete the .vnc folder before you do so
