### ISSUE TITLE
How to start & stop vncserver + help for proot apps

### ISSUE THREAD

**Issue by AKPR2007** [Yisus7u7/termux-desktop-xfce#78]
Please tell both commands

And also. How to run proot apps in this (like Firefox)
I assume to run proot apps i need to install Ubuntu from andronix app (I've done that before) & then execute the following command in reader.
Also do i need to install full desktop environment in Ubuntu or just cli

**Comment by JyanJohn** [comment]
#21

**Comment by AKPR2007** [comment]
> #21

I found it. Might as well close this

**Comment by JyanJohn** [comment]
@AKPR2007 you should check out the other issues before creating a new one
