### ISSUE TITLE
Error with the perl module

### ISSUE THREAD

**Issue by Yisus7u7** [Yisus7u7/termux-desktop-xfce#8]
@suhan-paradkar

Hello, I get this error when installing the module (I have all the necessary libraries installed) 

~ $ cpan install XML::Parser
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Mon, 24 May 2021 15:17:02 GMT
Running install for module 'XML::Parser'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring T/TO/TODDR/XML-Parser-2.46.tar.gz with Makefile.PL
"/data/data/com.termux/files/home/.cpan/build/XML-Parser-2.46-2/assertlibqlvjlqVi": error: Android 5.0 and later only support position-independent executables (-fPIE).

Expat must be installed prior to building XML::Parser and I can't find
it in the standard library directories. Install 'expat-devel' (or
'libexpat1-dev') package with your OS package manager. See 'README'.

Or you can download expat from:

http://sourceforge.net/projects/expat/

If expat is installed, but in a non-standard directory, then use the
following options to Makefile.PL:

    EXPATLIBPATH=...  To set the directory in which to find libexpat

    EXPATINCPATH=...  To set the directory in which to find expat.h

For example:

    perl Makefile.PL EXPATLIBPATH=/home/me/lib EXPATINCPATH=/home/me/include

Note that if you build against a shareable library in a non-standard location
you may (on some platforms) also have to set your LD_LIBRARY_PATH environment
variable at run time for perl to find the library.

No 'Makefile' created  TODDR/XML-Parser-2.46.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK

What if libexpat if I have it installed

**Comment by Yisus7u7** [comment]
@suhan-paradkar I already installed libyaml and it still fails

**Comment by suhan-paradkar** [comment]
You need libexpat... Not libyaml

**Comment by Yisus7u7** [comment]
@suhan-paradkar It's also installed, I still got error

**Comment by Yisus7u7** [comment]
![Screenshot_20210524-221746](https://user-images.githubusercontent.com/64093255/119434491-e4f52f00-bcdd-11eb-9aff-6b79ed85cacd.png)

**Comment by Yisus7u7** [comment]
Also run directly and

**Comment by suhan-paradkar** [comment]
Try 
```
cpan install XML::Parser EXPATLIBPATH=$PREFIX/lib EXPATINCPATH=$PREFIX/include
```

**Comment by Yisus7u7** [comment]
Also directly execute the Makefile with the parameters where the libexpat libraries were located, and it still says that it is not installed

@suhan-paradkar

**Comment by Yisus7u7** [comment]
~ $ cpan install XML::Parser EXPATLIBPATH=$PREFIX/lib EXPATINCPATH=$PREFIX/include
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Mon, 24 May 2021 15:17:02 GMT
Running install for module 'XML::Parser'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring T/TO/TODDR/XML-Parser-2.46.tar.gz with Makefile.PL
"/data/data/com.termux/files/home/.cpan/build/XML-Parser-2.46-6/assertlibP8WmOOvQ": error: Android 5.0 and later only support position-independent executables (-fPIE).

Expat must be installed prior to building XML::Parser and I can't find
it in the standard library directories. Install 'expat-devel' (or
'libexpat1-dev') package with your OS package manager. See 'README'.

Or you can download expat from:

http://sourceforge.net/projects/expat/

If expat is installed, but in a non-standard directory, then use the
following options to Makefile.PL:

    EXPATLIBPATH=...  To set the directory in which to find libexpat

    EXPATINCPATH=...  To set the directory in which to find expat.h

For example:

    perl Makefile.PL EXPATLIBPATH=/home/me/lib EXPATINCPATH=/home/me/include

Note that if you build against a shareable library in a non-standard location
you may (on some platforms) also have to set your LD_LIBRARY_PATH environment
variable at run time for perl to find the library.

No 'Makefile' created  TODDR/XML-Parser-2.46.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- NOT OK
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
HTTP::Tiny failed with code[404] message[Not Found]
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.gz
HTTP::Tiny failed with code[404] message[Not Found]

Trying with
    /data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309"
to get
    http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
--2021-05-24 22:23:31--  http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
Resolving www.cpan.org... 151.101.2.132, 151.101.66.132, 151.101.130.132, ...
Connecting to www.cpan.org|151.101.2.132|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-24 22:23:32 ERROR 404: Not Found.


    Function system("/data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309" "http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib" ")
    returned status 8 (wstat 2048), left
/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309 with size 0
    Warning: no success downloading '/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309'. Giving up on it.

Trying with
    /data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309"
to get
    http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
--2021-05-24 22:23:32--  http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
Resolving www.cpan.org... 151.101.2.132, 151.101.66.132, 151.101.130.132, ...
Connecting to www.cpan.org|151.101.2.132|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-24 22:23:32 ERROR 404: Not Found.


    Function system("/data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309" "http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib" ")
    returned status 8 (wstat 2048), left
/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309 with size 0
    Warning: no success downloading '/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309'. Giving up on it.
No external ftp command available

Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
HTTP::Tiny failed with code[404] message[Not Found]
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.gz
HTTP::Tiny failed with code[404] message[Not Found]

Trying with
    /data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309"
to get
    http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
--2021-05-24 22:23:34--  http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
Resolving www.cpan.org... 151.101.2.132, 151.101.66.132, 151.101.130.132, ...
Connecting to www.cpan.org|151.101.2.132|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-24 22:23:34 ERROR 404: Not Found.


    Function system("/data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309" "http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib" ")
    returned status 8 (wstat 2048), left
/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309 with size 0
    Warning: no success downloading '/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309'. Giving up on it.

Trying with
    /data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309"
to get
    http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
--2021-05-24 22:23:35--  http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib
Resolving www.cpan.org... 151.101.2.132, 151.101.66.132, 151.101.130.132, ...
Connecting to www.cpan.org|151.101.2.132|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-24 22:23:36 ERROR 404: Not Found.


    Function system("/data/data/com.termux/files/usr/bin/wget -O "/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309" "http://www.cpan.org/authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib" ")
    returned status 8 (wstat 2048), left
/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309 with size 0
    Warning: no success downloading '/data/data/com.termux/files/home/.cpan/sources/authors/id/E/E/E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib.tmp3309'. Giving up on it.
No external ftp command available

Please check, if the URLs I found in your configuration file
(http://www.cpan.org/) are valid. The urllist can be edited. E.g. with 'o
conf urllist push ftp://myurl/'

Could not fetch authors/id/E/E//E/EX/EXPATLIBPATH=/data/data/com.termux/files/usr/lib

**Comment by suhan-paradkar** [comment]
I am not able to reproduce it....!
[Screenshot_2021-05-25-08-53-58-66.jpg](https://user-images.githubusercontent.com/76830230/119434940-d5ee9b00-bd36-11eb-9b77-5a1fc7faa7af.jpg)
Have you installed libxml2 ?

**Comment by Yisus7u7** [comment]
> I am not able to reproduce it....!
> [Screenshot_2021-05-25-08-53-58-66.jpg](https://user-images.githubusercontent.com/76830230/119434940-d5ee9b00-bd36-11eb-9b77-5a1fc7faa7af.jpg)
> Have you installed libxml2 ?

@suhan-paradkar Yes

![Screenshot_20210524-222804](https://user-images.githubusercontent.com/64093255/119435230-5c778e00-bcdf-11eb-9361-3920dc55bb06.png)

**Comment by suhan-paradkar** [comment]
@Yisus7u7  Does that work??

**Comment by Yisus7u7** [comment]
No, and it fails to connect to the host

**Comment by suhan-paradkar** [comment]
> No, and it fails to connect to the host 

May be some connection issues.. It needs constant internet connection during installation
