### ISSUE TITLE
A tiny help

### ISSUE THREAD

**Issue by Aridlvory** [Yisus7u7/termux-desktop-xfce#83]
I changed the file location of the wallpaper and now Idk where was the original wallpaper location, and it's not shown in the list. Can u guys please tell me where it was

And thanks for creating such a wonderful project

![Screenshot_20220213-090933_AVNC.jpg](https://user-images.githubusercontent.com/78092537/153737637-45072a4e-9e77-4c13-beca-d29f3e3353fe.jpg)

**Comment by Yisus7u7** [comment]
> I changed the file location of the wallpaper and now Idk where was the original wallpaper location, and it's not shown in the list. Can u guys please tell me where it was 

The location of the default wallpapers are in `/data/data/com.termux/files/usr/share/backgrounds/xfce`

> And thanks for creating such a wonderful project

Thank you very much for your support, in the next update the themes will be more compact for a better experience on small screens, I will also separate the dependencies of the termux-desktop-xfce package into several independent packages for a more organized and clean installation, and I will fix the theme error in apps written in Qt
