### ISSUE TITLE
Issue on proot apps

### ISSUE THREAD

**Issue by Aridlvory** [Yisus7u7/termux-desktop-xfce#84]
Successfully installed firefox but I can't understand the language
![Screenshot_20220213-141505_AVNC.jpg](https://user-images.githubusercontent.com/78092537/153745800-cc1eb8b5-f0f1-4f78-b74e-6915022e8ad4.jpg)
This is what the terminal showed me when I typed the command
![Screenshot_20220213-141538_AVNC.jpg](https://user-images.githubusercontent.com/78092537/153745818-9351603f-ba58-4331-9f34-c70da0d101b1.jpg)

**Comment by Aridlvory** [comment]
Donno how but it fixed after sometime

**Comment by Yisus7u7** [comment]
Run:

`apk add ttf-dejavu`
