### ISSUE TITLE
Proot apps doesn't provide sound output

### ISSUE THREAD

**Issue by Aridlvory** [Yisus7u7/termux-desktop-xfce#85]
If I play some songs on YouTube via firefox it dosent provide sound output, but if I play some songs with audacious it produces sound

**Comment by Aridlvory** [comment]
Found the reason...![Screenshot_20220214-060442_AVNC.jpg](https://user-images.githubusercontent.com/78092537/153782626-b9642e4c-4d0c-477d-b6e0-6bbb501bf0b3.jpg)

**Comment by Yisus7u7** [comment]
Steps:

In termux :

```bash
pulseaudio --start --exit-idle-time=-1 

pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```

In proot:

```bash
apk add pulseaudio
Or
apt install pulseaudio 

And:

export PULSE_SERVER=127.0.0.1

firefox

Or

PULSE_SERVER=127.0.0.1 firefox &
