### ISSUE TITLE
Parole video player not working

### ISSUE THREAD

**Issue by Aridlvory** [Yisus7u7/termux-desktop-xfce#86]
https://user-images.githubusercontent.com/78092537/154509959-7e3fee77-e25d-427c-b0f3-03e3008e4045.mp4

**Comment by Yisus7u7** [comment]
> 2022_02_17_20_35_47.mp4

It is a termux error due to gstreamer update.

**Comment by ezbluntz** [comment]
Try my new "Frankenstein Termux Desktop. very easy installation.

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154767123-5bf06056-9e6a-4277-8c33-dfc6c8bea022.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154767177-6f1518cd-deb8-41d8-90b8-b66e8b38dee0.png)

![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154767202-546210e5-e4b8-45e4-ab5c-04b0882f4bbf.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154767224-fb84e9e0-6356-472a-8a6e-fb2e10e6c55b.png)

Enjoy

**Comment by themoonmeetsthesun** [comment]
> Try my new "Frankenstein Termux Desktop. very easy installation.
> 
> ![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154767123-5bf06056-9e6a-4277-8c33-dfc6c8bea022.png)
> 
> ![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154767177-6f1518cd-deb8-41d8-90b8-b66e8b38dee0.png)
> 
> ![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154767202-546210e5-e4b8-45e4-ab5c-04b0882f4bbf.png)
> 
> ![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154767224-fb84e9e0-6356-472a-8a6e-fb2e10e6c55b.png)
> 
> Enjoy

This is very wrong, I'll report you. Not a good thing to spam everywhere. I also have great projects but I don't spam everywhere.

**Comment by st0rmc4non** [comment]
For the acceleration: use Termux:x11 app and Wayland.

**Comment by themoonmeetsthesun** [comment]
> For the acceleration: use Termux:x11 app and Wayland.

Wayland works?

**Comment by Yisus7u7** [comment]
Solved, `pkg update`
