### ISSUE TITLE
VNC Server is broken

### ISSUE THREAD

**Issue by themoonmeetsthesun** [Yisus7u7/termux-desktop-xfce#89]
Hello! My vncserver is not working and all and I am not able to connect. I tried reinstalling and resetting termux too.
![image](https://user-images.githubusercontent.com/96462198/154833433-0d8eb733-d96f-4098-abe7-07f4f7f176f3.png)
![image](https://user-images.githubusercontent.com/96462198/154833435-2eb039ac-f329-4675-95c7-9e9b8424f2d9.png)

**Comment by themoonmeetsthesun** [comment]
Here is my system info:
![Screenshot_2022-02-20-14-29-49-53_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/96462198/154835565-7d9c4c0f-5056-4e2e-98af-48668ffacad8.jpg)

**Comment by Aridlvory** [comment]
What do u mean by reinstalling
Reinstalled termux and did everything again?

**Comment by Aridlvory** [comment]
Anyway try this
First run `killall Xvnc`
If there is any problem after that, try executing this again
```
rm -rf ~/.vnc/*pid*

rm -rf ~/.vnc/passwd

killall Xvnc
```



If this doesn't work wait until the author responds

**Comment by themoonmeetsthesun** [comment]
> What do u mean by reinstalling
> Reinstalled termux and did everything again?

I reset it from the app settings.

**Comment by themoonmeetsthesun** [comment]
> Anyway try this
> First run `killall Xvnc`
> If there is any problem after that, try executing this again
> ```
> rm -rf ~/.vnc/*pid*
> 
> rm -rf ~/.vnc/passwd
> 
> killall Xvnc
> ```
> 
> 
> 
> If this doesn't work wait until the author responds
> 
> This will delete and kill all the vnc connections in your device

It created a vnc session on localhost:2. I killed localhost:2 and that worked but I needed it to work in localhost:1 so I tried to kill it and that didn't work at expected. ![Screenshot_2022-02-20-16-48-37-24_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/96462198/154840004-fee39a4a-c004-49f7-b5d6-d0f13a23ea0d.jpg)

**Comment by themoonmeetsthesun** [comment]
Please help I restarted and it's still broken.

**Comment by Yisus7u7** [comment]
> Please help I restarted and it's still broken.

killall Xvnc

vncserver -listen tcp

**Comment by themoonmeetsthesun** [comment]
Thanks I'll try it when I get the phone

**Comment by themoonmeetsthesun** [comment]
I'll try it tommorow and will get back then.

**Comment by Whyle** [comment]
I found a works solution for me, first i switched repository to Tsinghua University mirror repository 
`termux-change-repo`
And then i do a upgrade
`apt upgrade`

Finally i try to start vncserver, and it's working.

**Comment by themoonmeetsthesun** [comment]
> > Please help I restarted and it's still broken.
> 
> killall Xvnc
> 
> vncserver -listen tcp 

It's not working at all 😞

**Comment by Aridlvory** [comment]
Looks like u gave up

**Comment by Aridlvory** [comment]
> I found a works solution for me, first i switched repository to Tsinghua University mirror repository 
> `termux-change-repo`
> And then i do a upgrade
> `apt upgrade`
> 
> Finally i try to start vncserver, and it's working.
> 

Changing repo and upgrading fixed it? 🤔

**Comment by themoonmeetsthesun** [comment]
> > I found a works solution for me, first i switched repository to Tsinghua University mirror repository
> > `termux-change-repo`
> > And then i do a upgrade
> > `apt upgrade`
> > Finally i try to start vncserver, and it's working.
> 
> Changing repo and upgrading fixed it? 🤔

I don't understand where the repo is located in there

**Comment by Aridlvory** [comment]
> It's completely failed. Setting and troubleshooting vncservers is so difficult. I'll remove it for now. I think this issue is related to Android 11 because it worked on my other phone with Android 8.1. 

I am in Android 11 too
Since I ran multiple vnc I had issues like this and the `killall Xvnc` command helped me
So it's not a A11 problem.. it's your device's problem

**Comment by Whyle** [comment]
> > > I found a works solution for me, first i switched repository to Tsinghua University mirror repository
> > > `termux-change-repo`
> > > And then i do a upgrade
> > > `apt upgrade`
> > > Finally i try to start vncserver, and it's working.
> > 
> > 
> > Changing repo and upgrading fixed it? 🤔
> 
> I don't understand where the repo is located in there

just type `termux-change-repo` command in Termux

**Comment by themoonmeetsthesun** [comment]
> > It's completely failed. Setting and troubleshooting vncservers is so difficult. I'll remove it for now. I think this issue is related to Android 11 because it worked on my other phone with Android 8.1. 
> 
> I am in Android 11 too
> Since I ran multiple vnc I had issues like this and the `killall Xvnc` command helped me
> So it's not a A11 problem.. it's your device's problem

I guess so

**Comment by themoonmeetsthesun** [comment]
> > > > I found a works solution for me, first i switched repository to Tsinghua University mirror repository
> > > > `termux-change-repo`
> > > > And then i do a upgrade
> > > > `apt upgrade`
> > > > Finally i try to start vncserver, and it's working.
> > > 
> > > 
> > > Changing repo and upgrading fixed it? 🤔
> > 
> > I don't understand where the repo is located in there
> 
> just type `termux-change-repo` command in Termux

That brings me to a place where it asks to change the repo to a specific mirror.

**Comment by themoonmeetsthesun** [comment]
Also I will try later to fix it. I have removed it for now. I'll see when I can fix it. Thanks for your help, really appreciate that.
