### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by Aridlvory** [Yisus7u7/termux-desktop-xfce#90]
Is it possible to run applications as appimage

**Comment by antonl05** [comment]
https://github.com/termux/termux-packages/issues/1278

**Comment by themoonmeetsthesun** [comment]
> Is it possible to run applications as appimage
> 

I think that it isn't supported.

**Comment by Yisus7u7** [comment]
https://github.com/termux/termux-packages/issues/1278#issuecomment-731402831

**Comment by Yisus7u7** [comment]
> > Is it possible to run applications as appimage
> 
> I think that it isn't supported. It's not supported on proot (I read somewhere) so how can it be supported on termux?

It is not supported because it requires special access to kernel functions (root).

**Comment by themoonmeetsthesun** [comment]
I didn't know about that thanks!

**Comment by Yisus7u7** [comment]
![Screenshot_20220220-105738](https://user-images.githubusercontent.com/64093255/154851639-5a196dff-83fa-4496-9dc7-d7ac95bc0422.png)

Since what they are here, so will be the new update.

**Comment by Aridlvory** [comment]
![Screenshot_20220221-203358_VNC Viewer.jpg](https://user-images.githubusercontent.com/78092537/154981194-caf07aea-d57a-433d-9a42-509265821f77.jpg)
