### ISSUE TITLE
Problem with mpv

### ISSUE THREAD

**Issue by VictorIvanPereira** [Yisus7u7/termux-desktop-xfce#95]
Hi, I have a problem when i run mpv -vo=x11 to see a video, the audio works well but the video is very laggy and the terminal says
 "[vo/x11/x11] XOpenIM() failed. Unicode input will not work.
[vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO."  and "Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field)." 
i was using a proot distro running chromium before and i can see video well so I don't think it is a problem of my hardware.

**Comment by themoonmeetsthesun** [comment]
I think I saw a similar issue here, so I think it's an issue with the project and not you.

**Comment by Yisus7u7** [comment]
> Hi, I have a problem when i run mpv -vo=x11 to see a video, the audio works well but the video is very laggy and the terminal says "[vo/x11/x11] XOpenIM() failed. Unicode input will not work. [vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO." and "Audio/Video desynchronisation detected! Possible reasons include too slow hardware, temporary CPU spikes, broken drivers, and broken files. Audio position will not match to the video (see A-V status field)." i was using a proot distro running chromium before and i can see video well so I don't think it is a problem of my hardware.

mpv is very slow to play video, that problem is normal. 

At the moment we have to wait for parole media player to be repaired
