### ISSUE TITLE
Manejo de librerías >.<

### ISSUE THREAD

**Issue by ETHLOB** [Yisus7u7/termux-desktop-xfce#99]
Hola Yisus, quisiera felicitarte por tu proyecto, en serio se siente muy fluido y casi como si estuviera en un pc de sobremesa jeje. Sí se percibe el avance respecto a la propuesta original de @adi1090x. Sólo quisiera saber una cosita, en caso de querer echar para atrás y desinstalar el framework, ¿qué habría que hacer? Es que lo estoy testeando en un celular de prueba. Gracias.

**Comment by Yisus7u7** [comment]
Te refieres a desinstalar termux-desktop?

**Comment by z8512** [comment]
Yes, please provide a uninstall script if possible.
Can you add termux:x11 app instead of realvnc viewer app?

**Comment by Yisus7u7** [comment]
> Yes, please provide a uninstall script if possible. Can you add termux:x11 app instead of realvnc viewer app?

### Uninstall

`apt autopurge termux-desktop-xfce xfce* tigervnc geany`
